version: "3"

services:
  backend:
    container_name: LegalLens-backend
    build:
      context: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./backend:/app
    depends_on:
      - firebase
    networks:
      - LegalLens-net

  frontend:
    container_name: LegalLens-frontend
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    environment:
      - REACT_APP_BACKEND_URL=http://backend:3000
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - LegalLens-net

  firebase:
    image: firebase:latest
    volumes:
      - ./backend/.env:/app/.env
    networks:
      - LegalLens-net

networks:
  LegalLens-net:
    driver: bridge
